# Site settings
title: One Star
email: onestar@briandavidhall.com
description: 42 reasons to ignore your critics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onestar.world" 
icon: /assets/images/favicon.png
author: Brian David Hall
permalink: /:title/

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num/"
hide_search: true
hide_credits: true
